version: '3'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:v10.7.0
    restart: always
    tty: true
    stdin_open: true
    privileged: true
    container_name: gitlab-runner
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/gitlab-runner/config:/etc/gitlab-runner"
