version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure