apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gcp-git-resource
  namespace: tekton-pipelines
spec:
  type: git
  params:
  - name: url
    value: http://gitlab.xxx.com/project/xxx.git
  - name: revision
    value: master