apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gcp-image-resource
  namespace: tekton-pipelines
spec:
  type: image
  params:
  - name: url
    value: xxx-registry.cn-beijing.cr.aliyuncs.com/project/app