apiVersion: v1
kind: Secret
metadata:
  name: gcp-image-secret
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: http://xxx-registry.cn-beijing.cr.aliyuncs.com/v1/
type: kubernetes.io/basic-auth
stringData:
    username: username
    password: ******