apiVersion: v1
kind: Secret
metadata:
  name: gcp-git-secret
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: http://gitlab.xxx.com
type: kubernetes.io/basic-auth
stringData:
  username: username
  password: "********"