apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gcp-maven-test
  namespace: tekton-pipelines
spec:
  resources:
    inputs:
      - name: src-git-repo
        type: git
  steps:
  - name: maven-test
    image: maven:3.5.0-jdk-8-alpine
    workingDir: /workspace/src-git-repo
    command:
      - mvn
    args:
      - test
    volumeMounts:
      - name:  m2
        mountPath:  /root/.m2
  volumes:
   - name: m2
     hostPath:
      path: /root/.m2