version: '3'
services:
  memcache:
    image: memcached:1.5.16
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "11211:11211"
    container_name: memcached-01
    command: [ "memcached","-m","128" ]

