# kubectl get Application  first-vela-app -oyaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  creationTimestamp: "2021-01-26T08:24:53Z"
  generation: 1
  name: first-vela-app
  namespace: default
  resourceVersion: "2662687"
  selfLink: /apis/core.oam.dev/v1alpha2/namespaces/default/applications/first-vela-app
  uid: a603e28a-b52a-4b5f-ae6c-be57de887c51
spec:
  components:
  - name: testsvc
    scopes:
      healthscopes.core.oam.dev: first-vela-app-default-health
    settings:
      image: crccheck/hello-world
      port: 8000
    traits:
    - name: route
      properties:
        domain: testsvc.example.com
    type: webservice