version: '2'
services:
  grafana:
    image: grafana/grafana:6.5.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin321
    # volumes:
      # - /data/grafana:/var/lib/grafana