# elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.3.2/elasticsearch-analysis-ik-6.3.2.zip
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    container_name: elasticsearch-01
    environment:
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
  elasticsearch_head:
    image: mobz/elasticsearch-head:5
    ports:
      - "9100:9100/tcp"
    container_name: elasticsearch_head
    environment:
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
