version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: kafka-zookeeper-01
    ports:
      - "2181:2181"
  kafka:
    image:  wurstmeister/kafka:latest
    container_name: kafka-broke-01
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
