version: '3'
services:
  mysql_compose-01:
    deploy:
      labels:
        com.example.description: "This label will appear on all containers for the web service"
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: mysql:5.7
    ports:
      - "3306:3306/tcp"
    volumes:
      - "/data/mysql/docker-compose-01:/var/lib/mysql"
    container_name: mysql_compose-01
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  mysql_compose-02:
    deploy:
      labels:
        com.example.description: "This label will appear on all containers for the web service"
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: mysql:5.7
    ports:
      - "3307:3306/tcp"
    container_name: mysql_compose-02
    volumes:
      - "/data/mysql/docker-compose-02:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
