version: '2'
services:
  nsqadmin:
    image: nsqio/nsq:latest
    ports:
      - "4171:4171/tcp"
    container_name: nsqadmin-01
    command: [ "nsqadmin", "--lookupd-http-address=10.171.195.61:4161" ]
  nsqd:
    image: nsqio/nsq:latest
    ports:
      - "4150:4150/tcp"
      - "4151:4151/tcp"
    container_name: nsqd-01
    command: [ "nsqd","--lookupd-tcp-address=10.171.195.61:4160","--broadcast-address=10.171.195.61" ]
  nsqlookupd:
    image: nsqio/nsq:latest
    ports:
      - "4160:4160/tcp"
      - "4161:4161/tcp"
    container_name: nsqlookupd-01
    command: [ "nsqlookupd" ]