version: '3'
services:
    redis:
      image: redis:5.0.0
      restart: always
      container_name: redis-01
      command: redis-server
      ports:
        - "6379:6379"
      volumes:
        - redisdb:/data

volumes:
  redisdb:

#  ["redis-server","--appendonly","yes","--requirepass","Jsx4uj2P8pveOCgz"]