version: '3'
services:
    redis:
      image: redis:5.0.0
      container_name: redis-01
      command: redis-server --requirepass 123456
      ports:
        - "16379:6379"
      volumes:
        - /data/redis-01:/data
