version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672/tcp"
      - "5672:5672/tcp"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_USER: "rabbitmq"