
# 连接dm

/opt/dmdbms/bin/disql SYSDBA/SYSDBA001@127.0.0.1:5236


# 创建用户
```
CREATE TABLESPACE DTEASYCARE DATAFILE 'DTEASYCARE.DBF' SIZE 128;

CREATE USER DTEASYCARE IDENTIFIED BY passwod123;

ALTER USER DTEASYCARE DEFAULT TABLESPACE DTEASYCARE DEFAULT INDEX TABLESPACE DTEASYCARE;

GRANT RESOURCE,VTI,SOI TO DTEASYCARE;
```

# 删除用户
```
DROP USER DTAGENT_INSIGHT CASCADE;
```


