version: '3'
services:
  dm8:
    image: dm8_single:v8.1.2.128_ent_x86_64_ctm_pack4
    container_name: dm8
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      LD_LIBRARY_PATH: "/opt/dmdbms/bin"
      UNICODE_FLAG: 1  # UNICODE_FLAG 字符集 (0)，可选值： 0[GB18030]， 1[UTF-8]， 2[EUC-KR]
      LENGTH_IN_CHAR: 0
      # SYSDBA_PWD: "SYSDBA001" # 默认密码就是SYSDBA001 这里修改默认密码不一定会起效，需要进数据库改
    ports:
      - "5236:5236"
    volumes:
      - ./data/dm8/data:/opt/dmdbms/data
    # restart: always
    networks:
      - my_net_dm
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          # cpus: 0.8
          memory: 1000M
networks:
  my_net_dm:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16