version: '2.3'
services:
  dm8:
    image: 872694792/dm8_single:v8.1.2.128_ent_x86_64_ctm_pack4
    container_name: dm8
    environment:
     
      TZ: Asia/Shanghai
      LD_LIBRARY_PATH: "/opt/dmdbms/bin"
      UNICODE_FLAG: 1  
      LENGTH_IN_CHAR: 0
      SYSDBA_PWD: "SYSDBA001" 
    ports:
      - "5236:5236"
    volumes:
      - dm_data:/opt/dmdbms/data
    restart: always

volumes:
  dm_data:


# UNICODE_FLAG 字符集 (0)，可选值： 0[GB18030]， 1[UTF-8]， 2[EUC-KR]
# 默认密码就是SYSDBA001 这里修改默认密码不一定会起效，需要进数据库改
# 时区上海