# vm.max_map_count = 262144 >> /etc/sysctl.conf
version: '3'
services:
  es01:
    image: registry.cn-hangzhou.aliyuncs.com/myun/elasticsearch:7.5.1
    container_name: es01
    environment:
      - node.name=es01
      - network.publish_host=172.16.200.76
      - network.host=0.0.0.0
      - cluster.name=es-docker-cluster
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.seed_hosts=172.16.200.76,172.16.137.118,172.16.137.119
      - cluster.initial_master_nodes=172.16.200.76,172.16.137.118,172.16.137.119
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms12g -Xmx12g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  data01:

---
version: '3'
services:
  es02:
    image: registry.cn-hangzhou.aliyuncs.com/myun/elasticsearch:7.5.1
    container_name: es02
    environment:
      - node.name=es02
      - network.publish_host=172.16.137.118
      - network.host=0.0.0.0
      - cluster.name=es-docker-cluster
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.seed_hosts=172.16.200.76,172.16.137.118,172.16.137.119
      - cluster.initial_master_nodes=172.16.200.76,172.16.137.118,172.16.137.119
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  data01:
---
version: '3'
services:
  es03:
    image: registry.cn-hangzhou.aliyuncs.com/myun/elasticsearch:7.5.1
    container_name: es03
    environment:
      - node.name=es03
      - network.publish_host=172.16.137.119
      - network.host=0.0.0.0
      - cluster.name=es-docker-cluster
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.seed_hosts=172.16.200.76,172.16.137.118,172.16.137.119
      - cluster.initial_master_nodes=172.16.200.76,172.16.137.118,172.16.137.119
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  data01:

---
version: '3'
services:
  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/myun/kibana:7.5.1
    ports:
      - "5601:5601"
    container_name: kibana01
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://172.16.200.76:9200","http://172.16.137.118:9200","http://172.16.137.119:9200"]'
      ELASTICSEARCH_URL: '["http://172.16.200.76:9200","http://172.16.137.118:9200","http://172.16.137.119:9200"]'
    volumes:
      - kibana01:/usr/share/kibana/config

volumes:
  kibana01: