version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: web
    tty: true
    ports:
      - "80:80"
      - "443:443"
    # volumes:
      # - "/root/cert:/etc/nginx/cert"
      # - "/root/conf/nginx.conf:/etc/nginx/nginx.conf"
      # - "/root/mudu_yc:/var/www/mudu_yc"


user nginx;
worker_processes auto;
worker_rlimit_nofile 65535;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  use epoll;
  worker_connections 1024;
}


http {

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;

    log_format main ' {
        "@timestamp": "$time_local", '
        '"remote_addr": "$remote_addr", '
        '"referer": "$http_referer", '
        '"request": "$request", '
        '"request_method": "$request_method", '
        '"status": $status, '
        '"bytes": $body_bytes_sent, '
        '"agent": "$http_user_agent", '
        '"x_forwarded": "$http_x_forwarded_for", '
        '"up_addr": "$upstream_addr",'
        '"up_host": "$upstream_http_host",'
        '"up_resp_time": "$upstream_response_time",'
        '"request_time": "$request_time"'
        '
    }
    ';


    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;


    gzip on;
    gzip_disable "msie6";

    server {
        listen 80;
        listen   443 ssl;
        server_name yaocu.mudu.tv;
        #设置长连接
        keepalive_timeout   70;

        ssl_certificate     /etc/nginx/cert/3536475__mudu.tv.pem;
        ssl_certificate_key /etc/nginx/cert/3536475__mudu.tv.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        root /var/www/mudu_yc;

        location / {
        }
  }
}