FROM ubuntu:16.04
MAINTAINER chenqiangjun "chenqiangjun@mudu.tv"

ENV HOME /root
ENV USER root
ENV TZ="Asia/Shanghai"
ENV SSH_KEY=
ARG GitHost

RUN echo 'deb http://mirrors.aliyun.com/ubuntu/ xenial main \n\
    deb-src http://mirrors.aliyun.com/ubuntu/ xenial main \n\
    deb http://mirrors.aliyun.com/ubuntu/ xenial-updates main \n\
    deb-src http://mirrors.aliyun.com/ubuntu/ xenial-updates main \n\
    deb http://mirrors.aliyun.com/ubuntu/ xenial universe \n\
    deb-src http://mirrors.aliyun.com/ubuntu/ xenial universe \n\
    deb http://mirrors.aliyun.com/ubuntu/ xenial-updates universe \n\
    deb-src http://mirrors.aliyun.com/ubuntu/ xenial-updates universe \n\
    deb http://mirrors.aliyun.com/ubuntu/ xenial-security main \n\
    deb-src http://mirrors.aliyun.com/ubuntu/ xenial-security main \n\
    deb http://mirrors.aliyun.com/ubuntu/ xenial-security universe \n\
    deb-src http://mirrors.aliyun.com/ubuntu/ xenial-security universe \n'\
    > /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y apt-transport-https curl software-properties-common python-software-properties language-pack-en-base
RUN LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg |  apt-key add - && \
    echo 'deb https://dl.yarnpkg.com/debian/ rc main' >/etc/apt/sources.list.d/yarn.list && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get update && \
    apt-get -yqq install ssh gcc vim git  wget build-essential software-properties-common libxrender1 nginx nscd supervisor net-tools php7.1 php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-mcrypt php7.1-zip php7.1-fpm php-memcached php-redis nodejs yarn

RUN yarn config set registry https://registry.npm.taobao.org/

RUN mkdir /root/.ssh/ -p && \
    echo $SSH_KEY | base64 --decode > /root/.ssh/id_rsa && \
    ssh-keyscan git.mudu.tv >> /root/.ssh/known_hosts && \
    chmod -R 600 /root/.ssh && \
    echo "Asia/Shanghai" > /etc/timezone

RUN sed -i "s/;date.timezone =.*/date.timezone = Asia\/Shanghai/" /etc/php/7.1/fpm/php.ini && \
    sed -i "s/;date.timezone =.*/date.timezone = Asia\/Shanghai/" /etc/php/7.1/cli/php.ini && \
    sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" /etc/php/7.1/fpm/php.ini && \
    sed -i "s/;opcache.enable=0/opcache.enable=1/" /etc/php/7.1/fpm/php.ini && \
    sed -i "s/;opcache.memory_consumption=.*/opcache.memory_consumption=128/" /etc/php/7.1/fpm/php.ini && \
    sed -i "s/;opcache.max_accelerated_files=.*/opcache.max_accelerated_files=8000/" /etc/php/7.1/fpm/php.ini && \
    sed -i "s/;opcache.revalidate_freq=.*/opcache.revalidate_freq=60/" /etc/php/7.1/fpm/php.ini && \
    sed -i "s/;opcache.fast_shutdown=.*/opcache.fast_shutdown=1/" /etc/php/7.1/fpm/php.ini && \
    sed -i "s/upload_max_filesize\s*=\s*.*/upload_max_filesize = 200M/" /etc/php/7.1/fpm/php.ini



RUN echo "${GitHost}" >> /etc/hosts && \
    git clone git@git.mudu.tv:dev-public/mudutv_web.git  /var/www/mudutv/ && \
    git clone git@git.mudu.tv:back-end/mudutv_web_golang.git /root/mudutv_web_golang

RUN echo `grep -v ${GitHost} /etc/hosts` > /etc/hosts

RUN echo 'cd /var/www/mudutv/  \n\
    git fetch \n\
    git reset --hard \n\
    git clean -n \n\
    git clean -f \n\
    git merge origin/master \n\
    supervisord  -c /etc/supervisor/supervisord.conf \n\
    service nginx start \n\
    service php7.0-fpm start \n'\
    > /start.sh

RUN chmod +x /start.sh
# docker build -t registry.cn-hangzhou.aliyuncs.com/mudu/mudutv-web:20200526  --build-arg GitHost='10.26.38.62 git.mudu.tv' .