version: "3"
services: 
  opentsdb:
    hostname: otsdb-host
    image: petergrace/opentsdb-docker:9aa7f88
    environment:
      - WAITSECS=30    
    ports:
      - 4242:4242
      - 60030:60030
    volumes:  
      - "/data/opentsdb:/data/hbase"