version: '2'
services:
  minio:
    image: minio/minio
    command: ["server","/data"]
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123456
    volumes: 
      - ./data:/data