version: '2'
services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - docker_net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kafka1
    ports:
      - "9092:9092"
    links:
      - zookeeper-server
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.75
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.75:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
    volumes:
      - "kafka1:/kafka"
    networks:
      - docker_net


  kafka2:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kafka2
    ports:
      - "9093:9092"
    links:
      - zookeeper-server
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.75
      KAFKA_ADVERTISED_PORT: 9093 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.75:9093
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
    volumes:
      - "kafka2:/kafka"
    networks:
      - docker_net

  kafka3:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kafka3
    ports:
      - "9094:9092"
    links:
      - zookeeper-server
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.75
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.75:9094
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-server:2181"
    volumes:
      - "kafka3:/kafka"
    networks:
      - docker_net

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper-server
    environment:
      ZK_HOSTS: zookeeper-server:2181
      TZ: CST-8
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.199.0/24
        gateway: 172.20.199.1

volumes:
  kafka1:
  kafka2:
  kafka3: