version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: kafka-zookeeper-01
    ports:
      - "2181:2181"
  kafka:
    image:  wurstmeister/kafka:latest
    container_name: kafka-broke-01
    links:
    - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.3.222
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  manager:    
    image: deltaprojects/kafka-manager
    container_name: kafka-manager
    links: 
    - zookeeper
    ports:
    - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: admin123
