# https://github.com/PeterGrace/opentsdb-docker
version: '3'
services:
  opentsdb:
    hostname: otsdb-host
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30    
    ports:
      - 4242:4242
      - 60030:60030
    volumes:  
      - "./data:/data/hbase"