version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306/tcp"
    volumes:
      - /data/atlassian/mysql:/var/lib/mysql
    container_name: atlassian_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "密码"
      TZ: "Asia/Shanghai"
  jira:
    image:  cptactionhank/atlassian-jira-software:8.1.0
    restart: always
    privileged: true
    ports:
      - "80:8080/tcp"
    volumes:
      - /data/atlassian/jira/jira:/var/atlassian/jira
  confluence:
    image: cptactionhank/atlassian-confluence:7.7.3
    restart: always
    privileged: true
    ports:
      - "8090:8090/tcp"
      - "8091:8091/tcp"
    volumes:
      - /data/atlassian/confluence/application-data:/var/atlassian/application-data/confluence
      - /data/atlassian/confluence/confluence:/var/atlassian/confluence