version: '3'
services:
  influxdb:
    image: influxdb:1.8.4
    environment:
      - INFLUXDB_DB=db0   
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yKkzXLpZMg2htbQ4
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=yKkzXLpZMg2htbQ4
    ports:
      - 8086:8086
    volumes:  
      - "/data/influxdb:/var/lib/influxdb"